# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 20e8b9cc93314832d9d44b847e5a0197865aa0b2224f16cf162e6cf942011cc58c7801dc96a8fb41f68e871d1c807a516232ad7203c28867513280874ad21b61

test:
  secret_key_base: 52d2834edd8337b92e0bbdc7125f8ccc917a0162c3a6ebe0455d855cf474c175807ace7799e5484fdfc27087a0931b1cfcad8f9701e81ef871bad13bb80ddcbb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
